name: Update Ocean Depth Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-depth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download 20m depth contour
        env:
          MSIL_API_KEY: ${{ secrets.MSIL_API_KEY }}
        run: |

          mkdir -p depth/20m

          curl -L \
            -H "Ocp-Apim-Subscription-Key: ${MSIL_API_KEY}" \
            "https://api.msil.go.jp/depth-contour/v2/MapServer/10/query?f=geojson&where=1%3D1&geometry=132.50%2C34.20%2C132.60%2C34.30&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&returnGeometry=true" \
            -o depth/20m/kure.json

      - name: Check file
        run: |
          ls -lh depth/20m/kure.json

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add depth/20m/kure.json

          git diff --cached --quiet || git commit -m "Update Kure 20m depth data"

          git push
